- name: check Linux distribution, CentOS 7 needed
  fail:
    msg: "Task failed as unexpected OS version found: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
  when:
    ansible_facts['distribution_version'] is version('7', '<') or
    'CentOS' != ansible_facts['distribution']


- name: setup tool to compile
  block:    
  - name: update yum
    shell: 
      cmd: "yum -y update"      

  - name: install simple common tools  
    package:
      name: 
        - git
        - rpm-build
        - java-1.8.0-openjdk-devel.x86_64
        - gcc-c++
        - python-devel
      state: present

  - name: install pip which depend on python-devel
    get_url:
      url: https://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg#md5=fe1f997bc722265116870bc7919059ea
      dest: /tmp/setuptools-0.6c11-py2.7.egg
      mode: '0440'   

  - name: run the setuptools-0
    shell: 
      cmd: "sh ./setuptools-0.6c11-py2.7.egg"
      chdir: /tmp

  - name : download maven 3.9.1 and decompress it
    unarchive:
      src: "https://dlcdn.apache.org/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz"
      dest: "/opt"
      remote_src: yes

  - name: creating a symlink for maven 3.9.1
    file:
      src: "/opt/apache-maven-3.9.1"
      dest: "/opt/maven"
      state: link

  - name: add maven system variable
    copy:
      src: maven.sh
      dest: /etc/profile.d/maven.sh
      mode: '0644'

  - name: source maven.sh
    shell: 
      cmd: "source /etc/profile.d/maven.sh"
  
  become: yes